name: dockerImagePush

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest    
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - uses: 'actions/checkout@v3'
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          token_format: 'access_token'
          workload_identity_provider: 'projects/55575348606/locations/global/workloadIdentityPools/pool1/providers/oidcprovider'
          service_account: 'github@mks02id.iam.gserviceaccount.com'

      # Login to a Docker registry
      # https://github.com/docker/login-action
      - name: login to Google Cloud Registry
        uses: docker/login-action@v2
        with:
          registry: us-central1-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      # Load server configuration files secrets 
      - name: load config files
        run: |
          mkdir config
          printf "${{secrets.CONFIG}}" > config/config.txt
          printf "${{secrets.SERVERSETTINGS}}" > config/serversettings.json
      
      # Build and push Docker image
      # https://github.com/docker/build-push-action
      - name: build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: us-central1-docker.pkg.dev/mks02id/docker/jmusicbait
